# Generated by Django 4.2.11 on 2024-03-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_qamodel_delete_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QAModel',
            new_name='voice_qamodel',
        ),
    ]
